# Generated by Django 5.2.5 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('designation_bn', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('join_date', models.DateField()),
                ('show_on_site', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('title_bn', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('content_bn', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('স্বাস্থ্যসেবা', 'স্বাস্থ্যসেবা'), ('প্রশিক্ষণ', 'প্রশিক্ষণ'), ('সহায়তা', 'সহায়তা'), ('সচেতনতা', 'সচেতনতা'), ('প্রতিবেদন', 'প্রতিবেদন'), ('অনুষ্ঠান', 'অনুষ্ঠান')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
